name: pfb_mobile
description: Perfect Family Builder.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/x8Bg.png
    - asset/x8Border.png
    - asset/x6Bg.png
    - asset/x6Border.png
    - asset/x5Bg.png
    - asset/x5Border.png
    - asset/x4Bg.png
    - asset/x4Border.png
