name: pfb_mobile
description: Perfect Family Builder.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  google_maps_flutter: ^2.1.2

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: asset/fonts/Montserrat-SemiBold.ttf

  assets:
    - asset/x8m.png
    - asset/x8f.png
    - asset/x6m.png
    - asset/x6f.png
    - asset/x5m.png
    - asset/x5f.png
    - asset/x4m.png
    - asset/x4f.png
    - asset/intro1.png
    - asset/intro2.png
    - asset/intro3.png
    - asset/login_bg.png
    - asset/x8.png
    - asset/x6.png
    - asset/x5.png
    - asset/x4.png
    - asset/x_4.png

    - asset/icon_drower.png
    - asset/icon_search.png
    - asset/icon_bell.png
    - asset/icon_home.png
    - asset/icon_chat.png
    - asset/icon_qanda.png
    - asset/icon_timeline.png
    - asset/icon_profile.png
    - asset/icon_home_w.png
    - asset/icon_chat_w.png
    - asset/icon_qanda_w.png
    - asset/icon_timeline_w.png
    - asset/icon_profile_w.png
    - asset/icon_pdf.png

    - asset/flags/91.jpg
    - asset/flags/971.jpg